image: java:11-jdk
stages:
  - build
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build:
  stage: build
  script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - ./gradlew build publish --stacktrace --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 days
  only:
    - master
  tags:
    - linux
    - x86
    - x86_64
